### ISSUE TITLE
bug: actions-gh-pages not working correctly

### ISSUE THREAD

**Issue by bdarcus** [citation-style-language/data-parsing#2]
Could you please help me figure this out @dhimmel? 

My plan is to use the working solution here on the main `schema` repo.

The files are getting correctly moved over to the gh-pages branch, but they're not getting published.

**Comment by dhimmel** [comment]
Probably the annoying github bug. workaround at https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token

> star First Deployment with GITHUB_TOKEN
The GITHUB_TOKEN has limitations for the first deployment so we have to select the GitHub Pages branch on the repository settings tab. After that, do the second deployment like the following pictures.

Should work for subsequent gh-pages commits after you select the gh-pages branch in settings.

**Comment by bdarcus** [comment]
That was indeed it. Thanks!

**Comment by bdarcus** [comment]
One other little thing.

Why ins't github serving the YAML files as utf-8?

I set the encoding on the `_config.yml` file, but `curl` says this:

```
content-type: text/yaml
```

JSON, OTOH, yields this:

```
content-type: application/json; charset=utf-8
```

**Comment by dhimmel** [comment]
Not sure GitHub Pages fully implements jekyll. Probably there is no way to control what content-type GitHub Pages puts in the header.
